<?xml version="1.0" encoding="utf-8"?><Database Name="JKDec20" Class="MyDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\MsSqlLocalDb;Initial Catalog=JKDec20;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="JKDec20ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserReg" Member="UserRegs">
    <Type Name="UserReg">
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserEmail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserFullName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserCityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserPhone" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="City_UserReg" Member="City" ThisKey="UserCityId" OtherKey="CityId" Type="City" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.City" Member="Cities">
    <Type Name="City">
      <Column Name="CityId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="City_UserReg" Member="UserRegs" ThisKey="CityId" OtherKey="UserCityId" Type="UserReg" />
    </Type>
  </Table>
</Database>